name: Manual work

on:
  workflow_dispatch:
  
jobs:
  
  build:
    if: github.ref == 'manual_work'
     #echo "${{ github.REF}}"
    #if: ${{ github.ref == 'ref:manual_work1' && github.ref == 'ref:manual_work'}}
   # if: ${{ github.ref == 'manual_work1' && github.ref == 'manual_work'}}
    #run: echo This event is a pull request that had an assignee removed.
    runs-on: ubuntu-latest
 
    steps:
    #- uses: ref:master/actions/checkout@v2
 
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    #- name: Build with Maven
     # run: |
        #    mvn -B package --file pom.xml
         #   mkdir staging && cp target/*.jar staging
           
    - name: cache for maven
      uses: actions/cache@v2
      with: 
          path: -/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
© 2022 GitHub, Inc.
Terms
Privacy
Security
Stat
