name: SimpleManualWork
on:
  workflow_dispatch:
  
  
  #push:
    #branches:
     # - master
     # - manual_work
      #- manual_work1
  
jobs:
  
  #build:
    #if: github.ref != 'refs/heads/master'
   # runs-on: ubuntu-latest
 
#jobs:
   This-worflow-is-enable-for-feature-brach-only:
   # if: github.ref != 'refs/heads/master
    runs-on: ubuntu-latest
    
    steps:
      - name: anusha
        run: |
          echo "::set-output name=action_fruit::strawberry"

      
