name: SimpleManualWork
on:
  workflow_dispatch:
  
  
  #push:
    #branches:
     # - master
     # - manual_work
      #- manual_work1
  
jobs:
  
  Enable-for-master-branch:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
 
#jobs:
   #This-worflow-is-enable-for-feature-brach-only:
   # if: github.ref != 'refs/heads/master
    #runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Enable for feature branch 
        run: |
            echo "This workflow is enable for Feature branch only"
        

      
