name: SimpleManualWork
on:
  workflow_dispatch:
  
  
  #push:
    #branches:
     # - master
     # - manual_work
      #- manual_work1
  
jobs:
  
  #build:
    #if: github.ref != 'refs/heads/master'
   # runs-on: ubuntu-latest
 
#jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: disable workflow commands
        run: |
          echo '::warning:: this is a warning'
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
          echo '::warning:: this will NOT be a warning'
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
          echo '::warning:: this is a warning again'
        
      
