name: SimpleManualWork
on:

  workflow_dispatch:
  push:
    ### if: "!contains(github.event.commits[0].message, '[skip ci]')"
    branches: [skip ci]
    
   

  
#jobs:
  
  #Disable-for-master-brach:
    #if: github.ref == 'ref/heads/manual_work'
    #echo "${{ github.REF}}"
    #if: ${{ github.ref == 'ref:manual_work1' && github.ref == 'ref:manual_work'}}
    # if: ${{ github.ref == 'manual_work1' && github.ref == 'manual_work'}}
    #run: echo This event is a pull request that had an assignee removed.
    #if: github.ref != 'refs/heads/master'
   # runs-on: ubuntu-latest
     #echo "The selected color is green" 
    
 
jobs:
  
  Disable-for-master-branch:
   
    if: github.ref != 'refs/heads/master'
     
    #if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    #runs-on: [skip ci]
   
#jobs:
   #This-worflow-is-enable-for-feature-brach-only:
   # if: github.ref != 'refs/heads/master
    #runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Disable for Master branch
        run: |
            echo "This workflow is disable for Master branch"
