name: SimpleManualWork
on:
  workflow_dispatch:
  
 # push:
   # branches:
     # - master
      #- manual_work
      #- manual_work1
  
jobs:
  
  Enable-for-feature-brach:
    #if: github.ref == 'ref/heads/manual_work'
    #echo "${{ github.REF}}"
    #if: ${{ github.ref == 'ref:manual_work1' && github.ref == 'ref:manual_work'}}
    # if: ${{ github.ref == 'manual_work1' && github.ref == 'manual_work'}}
    #run: echo This event is a pull request that had an assignee removed.
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
     #echo "The selected color is green" 
    
 
    steps:
      - uses: actions/checkout@v2
      - name: anusha
        run: |
            echo "this workflow enable for feature branch"
